import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/sidebar";
import ToggleContextProvider from "./components/toggleprovider";
import SidebarContextProvider from "./components/sidebarprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <ToggleContextProvider>
        <SidebarContextProvider>
          <body>
            <div className="container-fluid">
              <div className="row">
                <div className="col-md-1">
                  <Sidebar />
                </div>
                <div className="col-md-11">
                  {children}
                </div>
              </div>
            </div>
          </body>
        </SidebarContextProvider>
      </ToggleContextProvider>
    </html>
  );
}
